Vagrant.configure("2") do |config|
      config.vm.box = "bento/ubuntu-18.04"
    
      config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      vb.name = "testvagrant"
      vb.cpus = 2
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]  
      end
    
      config.vm.hostname = "testvagrant" 
    
      config.vm.provision "shell", inline: <<-SHELL
         apt-get update
         apt-get install -y python3 python3-pip
         sudo -H pip3 install psycopg2-binary
         sudo -H python3 -m pip install Django==3.0.6
         cp E:\sf_practice\file.txt /home/file.txt
      SHELL
    
    end
